aglio -i test.apib -o test.htmlFORMAT: 1A

# Polls

Polls is a simple API allowing consumers to view polls and vote in them.


### List All Questions [GET]
+ Response 200 (application/json)

        [
            {
                content: value,
                done: false
            }
        ]